### PR TITLE
Optimized Neural Net Regressor, Train error 8.7k Test Error 8.9k

### PR DESCRIPTION
**Pull request by utkuozbulak**

### CODE REVIEW

**Comment by utkuozbulak** [comment]
I changed the example I put before, this one is much more better and includes ways to export/import models with weights so that you can re-train.

8k is still far away from our target but it doesn't converge anymore, looking into ways to generate a better one.

**Comment by arahayrabedian** [comment]
if it works, get rid of the comments and chuck it in.

**Review by arahayrabedian — APPROVED** [review]
umm, as i was saying in a comment, if it works, ditch the comments and merge.

**Comment by alexdy2007** [comment]
approving only layer sizes and optimizer changes no need to really review if works

**Pull request merged**
